/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosnum;

import java.awt.Color;
import java.util.Calendar;

/**
 *
 * @author Uli Gibson
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
        setLang(0);
    }
    
    private void setLang(int id) {
        switch(id) {
            case 0: { //spanish
                lblTitle.setText("<html><center><font style=\"color: #5e9ca0;\" size=\"14\";>Acerca del desarrollador</font></center></html>");
                lblDescription.setText("<html>Mi nombre es Carlos Ulises, soy estudiante de la carrera de ingeniería <br/> en sistemas computacionales, me encanta todo lo relacionado con la tecnología, <br/> especialmente el area del desarrollo web. Constantemente estoy intentando aprender <br/>  nuevas tecnologías para poder mejorar mis habilidades en esa y otras areas.</html>");
                lblDescription1.setText("<html>Si quieres modificar este proyecto, solo te pido conserves mis créditos, ¡ gracias !.</html>");
                lblCopyright.setText("Todos los derechos reservados® copyright © 2010 - " + Calendar.getInstance().get(Calendar.YEAR));
                lblENG.setForeground(new Color(51,102,255));
                lblES.setForeground(new Color(102,102,102));
                break;
            }
            case 1: { //english
                lblTitle.setText("<html><center><font style=\"color: #5e9ca0;\" size=\"14\";>About developer</font></center></html>");
                lblDescription.setText("<html>My name is Carlos Ulises, I am student of software engineering career, <br/> I love everything related to technology and especially the development area. <br/> I am constantly learning more about the web development technologies for <br/> improve my skills in that area.</html>");
                lblDescription1.setText("<html>If you want to modify this project, please keep my credits. Thank you!.</html>");
                lblCopyright.setText("All rings reserved ® copyright © 2010 - " + Calendar.getInstance().get(Calendar.YEAR));
                lblENG.setForeground(new Color(102,102,102));
                lblES.setForeground(new Color(51,102,255));
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblCopyright = new javax.swing.JLabel();
        lblENG = new javax.swing.JLabel();
        lblES = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblDescription1 = new javax.swing.JLabel();
        lblWeb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acerca del desarrollador");
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("<html><center><font style=\"color: #5e9ca0; font-size:32px;\">About developer</font></center></html>");

        lblCopyright.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCopyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCopyright.setText("All rings reserved ® copyright © 2010 - 2019");

        lblENG.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblENG.setForeground(new java.awt.Color(51, 102, 255));
        lblENG.setText("English");
        lblENG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblENG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblENGMouseClicked(evt);
            }
        });

        lblES.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblES.setForeground(new java.awt.Color(102, 102, 102));
        lblES.setText("Spanish");
        lblES.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblESMouseClicked(evt);
            }
        });

        lblDescription.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDescription.setText("<html>Mi nombre es Carlos Ulises, soy estudiante de la carrera de ingeniería <br/>\nen sistemas computacionales, me encanta todo lo relacionado con la tecnología, <br/>\nespecialmente el area del desarrollo web. Constantemente estoy intentando aprender <br/> \nnuevas tecnologías para poder mejorar mis habilidades en esa y otras areas.</html>");

        lblPhoto.setText("<html><img src=\"https://raw.githubusercontent.com/CarlosUlisesOchoa/Reloj-Analogo-Alarma/master/src/img/dev%20profile.png\" alt=\"Developer photo\"/></html>");

        lblDescription1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDescription1.setText("<html>Si quieres modificar este proyecto, solo te pido conserves mis créditos, ¡ gracias !.</html>");

        lblWeb.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblWeb.setForeground(new java.awt.Color(0, 153, 255));
        lblWeb.setText("www.carlosulises.ml");
        lblWeb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWebMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(688, 688, 688)
                        .addComponent(lblES)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblENG)))
                .addGap(745, 745, 745))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTitle)
                        .addComponent(lblCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(497, 497, 497)
                        .addComponent(lblWeb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblES)
                            .addComponent(lblENG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(lblWeb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCopyright))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblESMouseClicked
        // TODO add your handling code here:
        setLang(0);
        
    }//GEN-LAST:event_lblESMouseClicked

    private void lblENGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblENGMouseClicked
        // TODO add your handling code here:
        setLang(1);
    }//GEN-LAST:event_lblENGMouseClicked

    private void lblWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWebMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblWebMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCopyright;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblENG;
    private javax.swing.JLabel lblES;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeb;
    // End of variables declaration//GEN-END:variables
}
